# Generated by Django 4.2.8 on 2023-12-06 16:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("photo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contest",
            name="internal_status",
            field=models.TextField(
                choices=[("open", "Open"), ("closed", "Closed"), ("draw", "Draw")],
                default="open",
            ),
        ),
        migrations.AddField(
            model_name="contest",
            name="voting_draw_end",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
