# Generated by Django 4.0.3 on 2022-04-14 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='date_end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='contest',
            name='date_start',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='contest',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='submission',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.TextField(verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.TextField(verbose_name='Last Name'),
        ),
    ]
