# Generated by Django 4.2.5 on 2023-11-27 15:06

from django.db import migrations
import photo.models


class Migration(migrations.Migration):
    dependencies = [
        ("photo", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", photo.models.UserManager()),
            ],
        ),
    ]
