# Generated by Django 4.2.5 on 2023-11-28 15:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("photo", "0002_alter_user_managers"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
