# Generated by Django 4.1 on 2022-09-06 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photo", "0002_alter_contest_date_end_alter_contest_date_start_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_contest_manager",
            field=models.BooleanField(default=False),
        ),
    ]
