# Generated by Django 4.2 on 2023-09-27 10:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("photo", "0002_alter_user_email"),
    ]

    operations = [
        migrations.RenameField(
            model_name="picture",
            old_name="picture_path",
            new_name="file",
        ),
    ]
