# Generated by Django 4.2.8 on 2024-01-23 10:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("photo", "0003_alter_contest_winners"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contest",
            name="prize",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="collection",
            name="pictures",
            field=models.ManyToManyField(
                blank=True, related_name="collection_pictures", to="photo.picture"
            ),
        ),
        migrations.AlterField(
            model_name="contestsubmission",
            name="votes",
            field=models.ManyToManyField(
                blank=True, related_name="submission_votes", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="picture",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="picture_likes", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
