# Generated by Django 4.2 on 2023-10-09 16:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("photo", "0003_rename_picture_path_picture_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="picture",
            name="name",
            field=models.TextField(blank=True, null=True),
        ),
    ]
