# Generated by Django 4.2 on 2023-05-31 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("photo", "0003_alter_contest_prize_alter_contest_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contest",
            name="cover_picture",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="photo.picture",
            ),
        ),
        migrations.AlterField(
            model_name="contest",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contest_created_by",
                to="photo.user",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_picture",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_picture_path",
                to="photo.picture",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_picture_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
