# Generated by Django 4.2.5 on 2023-10-17 09:13

from django.db import migrations, models
import photo.storages_backend


class Migration(migrations.Migration):
    dependencies = [
        ("photo", "0004_picture_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="picture",
            name="file",
            field=models.ImageField(
                storage=photo.storages_backend.PublicMediaStorage(),
                upload_to=photo.storages_backend.picture_path,
            ),
        ),
    ]
