# Generated by Django 4.2.5 on 2023-10-26 16:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("photo", "0004_picture_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last login"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="password",
            field=models.CharField(
                default="password", max_length=128, verbose_name="password"
            ),
            preserve_default=False,
        ),
    ]
