# Generated by Django 4.2 on 2023-06-09 08:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("photo", "0004_alter_contest_cover_picture_alter_contest_created_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contest",
            name="upload_phase_end",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contest",
            name="voting_phase_end",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
