# Generated by Django 4.2.5 on 2023-10-19 09:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("photo", "0005_alter_picture_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="contest",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="contestsubmission",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="picture",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="picturecomment",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", "False")),
                fields=("email",),
                name="user_email",
            ),
        ),
    ]
