# Generated by Django 4.1 on 2022-10-28 11:54

from django.db import migrations, models
import photo.models


class Migration(migrations.Migration):

    dependencies = [
        ("photo", "0005_alter_submission_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="content",
            field=models.ImageField(
                blank=True, null=True, storage=photo.models.SubmissionContentStorage, upload_to=photo.models.upload_path
            ),
        ),
    ]
