# Generated by Django 4.2 on 2023-06-27 08:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("photo", "0005_alter_contest_upload_phase_end_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contest",
            name="active",
        ),
    ]
