# Generated by Django 4.1 on 2022-11-07 17:53

from django.db import migrations, models
import photo.models


class Migration(migrations.Migration):

    dependencies = [
        ("photo", "0005_alter_submission_content"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="submission",
            name="content",
        ),
        migrations.AddField(
            model_name="submission",
            name="url",
            field=models.ImageField(
                blank=True, null=True, storage=photo.models.SubmissionContentStorage, upload_to=photo.models.upload_path
            ),
        ),
        migrations.AlterField(
            model_name="contest",
            name="created_by",
            field=models.UUIDField(blank=True, null=True, verbose_name="created by"),
        ),
    ]
