# Generated by Django 4.2 on 2023-07-07 08:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("photo", "0006_remove_contest_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contest",
            name="upload_phase_start",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
