# Generated by Django 4.1 on 2022-10-28 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("photo", "0006_alter_submission_content"),
    ]

    operations = [
        migrations.RenameField(
            model_name="submission",
            old_name="content",
            new_name="url",
        ),
    ]
