# Generated by Django 4.1 on 2022-10-28 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photo", "0007_rename_content_submission_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contest",
            name="created_by",
            field=models.UUIDField(blank=True, null=True, verbose_name="created by"),
        ),
    ]
