# Generated by Django 4.2 on 2023-07-17 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("photo", "0007_alter_contest_upload_phase_start"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_picture",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_picture",
                to="photo.picture",
            ),
        ),
    ]
