# Generated by Django 4.2 on 2023-08-04 08:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("photo", "0008_alter_user_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="picture",
            name="picture_path",
            field=models.ImageField(upload_to="pictures/"),
        ),
    ]
