# Generated by Django 4.2.5 on 2023-09-25 15:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("photo", "0009_alter_picture_picture_path"),
    ]

    operations = [
        migrations.RenameField(
            model_name="picture",
            old_name="picture_path",
            new_name="file",
        ),
    ]
