# Generated by Django 4.2 on 2023-09-25 10:28

from django.db import migrations, models
import photo.storages_backend


class Migration(migrations.Migration):
    dependencies = [
        ("photo", "0010_alter_picture_picture_path"),
    ]

    operations = [
        migrations.AlterField(
            model_name="picture",
            name="picture_path",
            field=models.FileField(
                storage=photo.storages_backend.PublicMediaStorage(), upload_to=""
            ),
        ),
    ]
